export interface searchUser {
    allPosts:[],
    country:string,
    coverPicture:string,
    livesIn:string,
    profilePicture:string,
    relationship:string,
    firstname:string,
    worksAt:string,
    followers:[],
    following:[],
    lastname:string,
    username:string,
    _id:string,
}