export interface userDetails {
    Notifications:[],
    country:string,
    coverPicture:string,
    livesIn:string,
    profilePicture:string,
    relationship:string,
    firstname:string,
    worksAt:string,
    followers:[],
    following:[],
    lastname:string,
    saved:[],
    username:string,
    _id:string,
}